# Generated by Django 5.0.4 on 2024-04-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tintuc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giaidau',
            name='tenGD',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
